name: Build and deploy Backend to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      env_vars: |
        SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}
        SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}
        SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASS }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker ${{ vars.GC_REGION }}-docker.pkg.dev

      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_URL }} .

      - name: Docker Push
        run: docker push ${{ env.IMAGE_URL }}

      - name: Update Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: ${{ vars.GC_REGION }}
          service: ${{ vars.GC_SERVICE_NAME }}
          image: ${{ env.IMAGE_URL }}
          env_vars: |
            SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASS }}
